### ISSUE TITLE
Container Images are private?

### ISSUE THREAD

**Issue by m4us1ne** [potibm/kasseapparat#244]
Pulling kasseapparat right now is not possible.

`root@deadline:/opt/kasseapparat# docker pull ghcr.io/potibm/kasseapparat:latest
Error response from daemon: Head "https://ghcr.io/v2/potibm/kasseapparat/manifests/latest": unauthorized`

**Comment by m4us1ne** [comment]
![image](https://github.com/user-attachments/assets/07437897-2232-4078-9579-623b11c4d1f6)
github also mentions that there are no packages available

**Comment by potibm** [comment]
Sorry, should be available now...

**Comment by m4us1ne** [comment]
works for on my end now
