### ISSUE TITLE
Templates currently not in the container

### ISSUE THREAD

**Issue by m4us1ne** [potibm/kasseapparat#245]
i created an account following the admin docoumentation, but got an error log
`2024/09/12 12:44:35 Error sending email Failed to parse email template: open templates/mail/token_new_user.txt: no such file or directory`
i found templates in the repo in backend/templates/ but could not find that folder inside the container. is that built in? or am i doing something wrong?

**Comment by potibm** [comment]
Sorry, should be fixed in v1.13.7

**Comment by m4us1ne** [comment]
no problem. I found a workaround that uses the demo feature to initialize an admin user and worked from there creating/deleting stuff until I got a clean state.

**Comment by m4us1ne** [comment]
sending password reset mails gives me an:
`kasseapparat    | 2024/09/13 09:32:02 Error sending email EOF`

**Comment by potibm** [comment]
@m4us1ne i will try to add some tests to the mail functionality :) any chance that this might occur while sending out? are you sure about the smtp settings?

**Comment by m4us1ne** [comment]
yeah the smtp settings were wrong. i havent worked with those smtp connection strings and it seems they require some sort of escaping.
