### ISSUE TITLE
On creating a new entry under "list entries" only the last 25 lists are shown in the list selector

### ISSUE THREAD

**Issue by RamsesUTL** [potibm/kasseapparat#266]

**Comment by potibm** [comment]
The field is an autocomplete field, so typing should search through the available list.

This was fixed in #192

**Comment by RamsesUTL** [comment]
Typing narrows it in but should a scrollable list not contain all items from the start? I found that really confusing from the user view.

**Comment by potibm** [comment]
I am using react admin here. They probably have to think of cases where thousands of items are in such a list -- which would make "containing all" pretty unusable... https://marmelab.com/react-admin/AutocompleteInput.html. 

For me it does not make sense to code this on my own, so I would rather suggest to open a ticket there.
