### ISSUE TITLE
Docker Images dont use semantic versioning

### ISSUE THREAD

**Issue by m4us1ne** [potibm/kasseapparat#283]
seems like the the github actions workflow does not push the full image tag to the registry.

**Comment by potibm** [comment]
So you need the images with patch level? Or am I missing something here?

**Comment by m4us1ne** [comment]
yeah that's right. it helps with image pinning and updating via renovate or dependabot

**Comment by potibm** [comment]
Alright. That should be an easy one...

**Comment by potibm** [comment]
Seems to be fixed. Can you confirm, please?

**Comment by m4us1ne** [comment]
yes new images are correctly tagged
